### ISSUE TITLE
Investigate PATCH - WPS - CSS observation

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#144]

**Comment by michielbdejong** [comment]
Pair programming with @mrvahedi68 here.
Running `./run-against-css.sh ` on the `n3-syntax-fix` branch of solid-crud-tests, against CSS commit 0a84230307 (main branch of 18 May), we're seeing some failing tests regarding missing WPS `pub` message when doing a PATCH. Maybe the test is not waiting long enough? Investigating.

**Comment by mrvahedi68** [comment]
The output of test:
 Expected: ArrayContaining ["ack http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl", "pub http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl"]
    Received: ["protocol solid-0.1", "warning Unrecognized message format: auth ", "warning Unrecognized message format: dpop ", "ack http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl"]

**Comment by michielbdejong** [comment]
With that branch of solid-crud-tests, I'm seeing these test failures for CSS:
1. Update › Using PATCH to replace triple (same content) › WPS  emits websockets-pubsub on the resource
2. Update › Using PATCH to replace triple (present) › updates the resource
3. Update › Using PATCH to replace triple (present) › WPS  emits websockets-pubsub on the resource
4. Concurrency › Use PATCH 10 times to add triple to the same resource › succeeds 10 times
5. Concurrency › Use PATCH 10 times to add triple to the same resource › updates the resource
6. Concurrency › Use PATCH 10 times to add triple to the same resource › WPS  emits websockets-pubsub on the resource 10 times

Of these, we're investigating only 1, 3, and 6 in this issue.

**Comment by michielbdejong** [comment]
In one window:
```
CommunitySolidServer$ npm start
```
In second window:
```
$ wscat -c http://localhost:3000
Connected (press CTRL+C to quit)
< protocol solid-0.1
< warning Missing Sec-WebSocket-Protocol header, expected value 'solid-0.1'
> sub http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
< ack http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
< pub http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
< pub http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
```
In third window:
```
$ cat test.ttl 
@prefix : <#>.

:hello :linked :world.
$ curl -X PUT -d @test.ttl http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
$ curl http://localhost:3000/solid-crud-tests-1654077454653/exists/exists4.ttl
@prefix : <#>.:hello :linked :world.

```

Actually 2 might be causing 3, so let's investigate 2 first.
https://github.com/solid-contrib/solid-crud-tests/blob/26ee194/test/surface/update.test.ts#L359

**Comment by michielbdejong** [comment]
Ah, there's a `.` that should be a `;` in that patch.

**Comment by michielbdejong** [comment]
Fixing this in https://github.com/solid-contrib/solid-crud-tests/commit/85d56089602225c1e37a8115dae0c5fd4cafaf91
