### ISSUE TITLE
23Q3 test runs

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#160]
Refering to https://solidservers.org/#table we want to do some overdue maintenance:

* [x] check if 1. passes the tests in latest default branch
* [x] check if 2. passes the tests in latest default branch
* [x] check if 3. passes the tests in latest default branch
* [ ] set up CI for 4.
* [ ] update 4. to latest upstream from 5.
* [ ] test latest default branch of 5. on localhost
* [ ] test live deployment of 6.
* [ ] test live deployment of 7.

**Comment by mrvahedi68** [comment]
I think we have incorrect data in the  [table](https://solidservers.org/#table). 
Number 2 and 3 have same links.
The correct one is : https://github.com/pdsinterop/solid-nextcloud

**Comment by mrvahedi68** [comment]
For item number 3: The tests are being executed within each pull request, but currently, the action is failing due to a permission issue.

**Comment by mrvahedi68** [comment]
I started to add tests to https://github.com/pdsinterop/community-server forked in https://github.com/mrvahedi68/community-server

**Comment by michielbdejong** [comment]
For item number 4: https://github.com/pdsinterop/community-server/issues/16

**Comment by michielbdejong** [comment]
Summary so far:
* NSS is OK https://github.com/nodeSolidServer/node-solid-server/pull/1737
* Solid-Nextcloud is OK https://github.com/pdsinterop/solid-nextcloud/actions/runs/4091354664/job/11108071845

To do today:
* [ ] php-solid-server is failing -> https://github.com/pdsinterop/php-solid-server/issues/52
* [ ] for CSS we have https://github.com/pdsinterop/community-server/issues/16 
* [ ] Test Inrupt Code Spaces and TrinPod

**Comment by michielbdejong** [comment]
Splitting this issue out into:
* https://github.com/pdsinterop/php-solid-server/issues/52
* https://github.com/pdsinterop/community-server/issues/16
* https://github.com/solid-contrib/solid-crud-tests/issues/68
* https://github.com/solid-contrib/solid-crud-tests/issues/69
