### ISSUE TITLE
non-deterministic outcome in RDF-based tests

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#28]
The first time I ran the tests, the number of passed RDF-based tests was 3,3,2,4 (as documented now in the README). The second time I ran them, it was 4,2,2,4.

**Comment by kjetilk** [comment]
Please recheck with the latest Web::Solid::Test::Basic. I have now made it skip `Date` headers, which had content that could change.

**Comment by kjetilk** [comment]
Assuming :+1: meant that I can close :-)
