### ISSUE TITLE
rename ResponseMessage to something that mentions assertions

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#50]
Instead of `:check_acl_location_res a http:ResponseMessage` have something like `:check_acl_location_res a test_suite:assertionList`

**Comment by kjetilk** [comment]
I noted the consensus to be something like 
```
 test:responseAssertion :put_new_acl_res 
```
i.e. it is the predicate, but yeah, I'll get right to it.

**Comment by kjetilk** [comment]
Fixed in #53
