### ISSUE TITLE
Fix or remove basic rdf-fixtures tests

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#69]
I submitted a PR to https://github.com/kjetilk/p5-web-solid-test-basic/pull/9 to fix the basic rdf-fixtures tests, but according to @kjetilk it's better to remove those tests rather than fix them.

**Comment by kjetilk** [comment]
Yeah, I tend to think that the HTTP list tests is generally preferred as they are much more advanced. 

There are some tests, like the test to check that `HEAD` and `GET` are the same that are kinda useful, so I haven't quite made up my mind yet, but it isn't a big priority to find out right now.

**Comment by michielbdejong** [comment]
Immediately, we should either start to fix or start to remove them. We can work slowly but we can't decide to stand still.
