### ISSUE TITLE
Inrupt-Test uses non-existing branch dev

### ISSUE THREAD

**Issue by ChristophKnabe** [solid/test-suite#75]
When executing the test of the Inrupt POD server by `./runTests.sh inrupt-pod-server` it fails with the error message `error: pathspec 'dev' did not match any file(s) known to git.` when executing `RUN git checkout dev` inside the Docker container.
At https://github.com/inrupt/pod-server/tree/master we can see, that there is no `dev` branch of the Inrupt POD server.
Please modify the branch to be used in the `Dockerfile`!
Using a non-existent branch causes failure of the final comparison table generation.
If you tell me, which branch is the best to use, I can file a Pull Request, as well.

**Comment by kjetilk** [comment]
Uh, oh... @michielbdejong , could you have a look?

**Comment by michielbdejong** [comment]
Fixed in #76
